name = "recipe-management"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "recipe-database"
database_id = "YOUR_D1_DATABASE_ID"